/**
 * AutoTrace Auto-Remediation Webhook — Vercel Serverless Function
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * POST /api/webhooks/github-pr
 *
 * Receives an AI-generated unified diff from the Django backend after triage,
 * creates a branch, applies the patch, and opens a Pull Request on GitHub.
 *
 * Environment Variables (set in Vercel dashboard):
 *   GITHUB_ACCESS_TOKEN      — GitHub PAT with `repo` scope
 *   AUTOTRACE_WEBHOOK_SECRET — shared secret for request authentication
 *   AUTOTRACE_DASHBOARD_URL  — base URL for incident links (optional)
 *   AUTOTRACE_PR_REVIEWERS   — comma-separated list of GitHub usernames (optional)
 */

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Apply a unified diff to a source string.
 * Handles hunks of the form @@ -start,count +start,count @@
 * Includes line-shift tolerance by matching removal content when line numbers drift.
 * Returns the patched string or throws on failure.
 */
function applyUnifiedDiff(original, diff) {
  const srcLines = original.replace(/\r\n/g, '\n').split('\n');
  const diffLines = diff.replace(/\r\n/g, '\n').split('\n');
  const result = [...srcLines];
  let offset = 0; // tracks cumulative line shifts from prior hunks

  for (let i = 0; i < diffLines.length; i++) {
    const line = diffLines[i];

    // Parse hunk header: @@ -oldStart,oldCount +newStart,newCount @@
    const hunkMatch = line.match(/^@@\s+-(\d+)(?:,(\d+))?\s+\+(\d+)(?:,(\d+))?\s+@@/);
    if (!hunkMatch) continue;

    const oldStart = parseInt(hunkMatch[1], 10);
    const removals = [];
    const additions = [];
    let contextBefore = 0;
    let hunkParsed = false;

    for (let j = i + 1; j < diffLines.length; j++) {
      const dl = diffLines[j];
      if (dl.startsWith('@@') || dl.startsWith('diff ') || dl.startsWith('---') || dl.startsWith('+++')) {
        break;
      }
      if (dl.startsWith('-')) {
        removals.push(dl.substring(1));
      } else if (dl.startsWith('+')) {
        additions.push(dl.substring(1));
      } else if (dl.startsWith(' ') || dl === '') {
        // context line — if we haven't seen any +/- yet, it's leading context
        if (removals.length === 0 && additions.length === 0) {
          contextBefore++;
        }
      }
      hunkParsed = true;
    }

    if (!hunkParsed && removals.length === 0 && additions.length === 0) continue;

    // Calculate initial splice position (0-indexed)
    let spliceStart = Math.max(0, oldStart - 1 + contextBefore + offset);

    // Line shift recovery: if removals are defined, search +/- 20 lines for matching removal anchor
    if (removals.length > 0 && removals[0].trim()) {
      const firstRemoval = removals[0].trim();
      const searchStart = Math.max(0, spliceStart - 20);
      const searchEnd = Math.min(result.length, spliceStart + 20);
      for (let k = searchStart; k < searchEnd; k++) {
        if (result[k] && result[k].trim() === firstRemoval) {
          spliceStart = k;
          break;
        }
      }
    }

    // Remove old lines and insert new ones
    result.splice(spliceStart, removals.length, ...additions);
    offset += additions.length - removals.length;
  }

  return result.join('\n');
}

/**
 * Build a rich Markdown PR body.
 */
function buildPRBody({ incident_id, error_type, error_message, ai_root_cause_summary, file_path, stack_trace, dashboard_url }) {
  const dashboardLink = dashboard_url
    ? `[View Incident on AutoTrace Dashboard](${dashboard_url}/incidents/${incident_id})`
    : `Incident ID: \`${incident_id}\``;

  return `## 🤖 AutoTrace Auto-Remediation

> This Pull Request was automatically generated by the **AutoTrace AI Triage Engine** after detecting and analyzing a production crash.

### 🔍 Root Cause Analysis

${ai_root_cause_summary}

---

### 📋 Incident Details

| Field | Value |
|-------|-------|
| **Incident ID** | \`${incident_id}\` |
| **Error Type** | \`${error_type}\` |
| **Error Message** | ${error_message || 'N/A'} |
| **Affected File** | \`${file_path}\` |
| **Dashboard** | ${dashboardLink} |

${stack_trace ? `### 📜 Stack Trace\n\`\`\`\n${stack_trace}\n\`\`\`` : ''}

---

> **⚠️ Review Required**: This fix was generated by AI. Please review the changes carefully before merging.
`;
}

// ---------------------------------------------------------------------------
// GitHub API helpers (using native fetch — zero dependencies)
// ---------------------------------------------------------------------------

async function githubAPI(method, endpoint, token, body = null) {
  const url = `https://api.github.com${endpoint}`;
  const headers = {
    'Authorization': `Bearer ${token}`,
    'Accept': 'application/vnd.github+json',
    'X-GitHub-Api-Version': '2022-11-28',
    'User-Agent': 'AutoTrace-Webhook/1.0',
  };
  if (body) headers['Content-Type'] = 'application/json';

  const res = await fetch(url, {
    method,
    headers,
    body: body ? JSON.stringify(body) : undefined,
  });

  const data = await res.json().catch(() => ({}));
  if (!res.ok) {
    const msg = data.message || res.statusText;
    throw new Error(`GitHub API ${method} ${endpoint} failed (${res.status}): ${msg}`);
  }
  return data;
}

// ---------------------------------------------------------------------------
// Main handler
// ---------------------------------------------------------------------------

export default async function handler(req, res) {
  // Only accept POST
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  // 1. Authenticate request
  const webhookSecret = process.env.AUTOTRACE_WEBHOOK_SECRET;
  const authHeader = req.headers['authorization'] || req.headers['Authorization'];
  const incomingSecret = 
    req.headers['x-webhook-secret'] || 
    req.headers['X-Webhook-Secret'] || 
    req.headers['X-WEBHOOK-SECRET'] ||
    (authHeader && authHeader.replace(/^Bearer\s+/i, ''));

  if (!webhookSecret || incomingSecret !== webhookSecret) {
    return res.status(401).json({ error: 'Unauthorized: invalid or missing webhook secret' });
  }

  // 2. Validate payload
  const {
    incident_id,
    error_type,
    error_message,
    file_path,
    unified_diff,
    ai_root_cause_summary,
    target_repo,
    stack_trace,
    reviewers: customReviewers,
  } = req.body || {};

  if (!incident_id || !error_type || !file_path || !unified_diff || !ai_root_cause_summary) {
    return res.status(400).json({
      error: 'Missing required fields',
      required: ['incident_id', 'error_type', 'file_path', 'unified_diff', 'ai_root_cause_summary'],
    });
  }

  if (!target_repo || !target_repo.includes('/')) {
    return res.status(400).json({
      error: 'Missing or invalid target_repo (expected format: "owner/repo")',
    });
  }

  // 3. Validate environment
  const githubToken = process.env.GITHUB_ACCESS_TOKEN;
  if (!githubToken) {
    return res.status(500).json({ error: 'Server misconfiguration: GITHUB_ACCESS_TOKEN not set' });
  }

  const dashboardUrl = (process.env.AUTOTRACE_DASHBOARD_URL || '').replace(/\/+$/, '');
  const [repoOwner, repoName] = target_repo.split('/');
  const branchName = `autotrace-fix/${incident_id}`;

  // Configure reviewer & assignee lists
  const defaultReviewer = 'rajjadhav55';
  const reviewers = Array.isArray(customReviewers) && customReviewers.length > 0
    ? customReviewers
    : (process.env.AUTOTRACE_PR_REVIEWERS
      ? process.env.AUTOTRACE_PR_REVIEWERS.split(',').map(r => r.trim()).filter(Boolean)
      : [defaultReviewer]);

  try {
    // 4. Retrieve repository details to discover default branch (main/master)
    const repoInfo = await githubAPI('GET', `/repos/${repoOwner}/${repoName}`, githubToken);
    const defaultBranch = repoInfo.default_branch || 'main';

    // 5. Get latest commit SHA of the default branch
    const refData = await githubAPI('GET', `/repos/${repoOwner}/${repoName}/git/ref/heads/${defaultBranch}`, githubToken);
    const baseSha = refData.object.sha;

    // 6. Create the fix branch
    try {
      await githubAPI('POST', `/repos/${repoOwner}/${repoName}/git/refs`, githubToken, {
        ref: `refs/heads/${branchName}`,
        sha: baseSha,
      });
    } catch (branchErr) {
      // Branch may already exist from a previous attempt — continue
      if (!branchErr.message.includes('Reference already exists')) {
        throw branchErr;
      }
    }

    // 7. Get the affected file content from the default branch
    const fileData = await githubAPI(
      'GET',
      `/repos/${repoOwner}/${repoName}/contents/${encodeURIComponent(file_path)}?ref=${defaultBranch}`,
      githubToken
    );

    const originalContent = Buffer.from(fileData.content, 'base64').toString('utf-8');

    // 8. Apply the unified diff
    let patchedContent;
    try {
      patchedContent = applyUnifiedDiff(originalContent, unified_diff);
    } catch (diffErr) {
      return res.status(422).json({
        error: 'Failed to apply unified diff to file',
        detail: diffErr.message,
      });
    }

    // 9. Commit the patched file to the fix branch
    const patchedBase64 = Buffer.from(patchedContent, 'utf-8').toString('base64');

    await githubAPI(
      'PUT',
      `/repos/${repoOwner}/${repoName}/contents/${encodeURIComponent(file_path)}`,
      githubToken,
      {
        message: `AutoTrace: automated fix for ${error_type} (incident ${incident_id})`,
        content: patchedBase64,
        sha: fileData.sha,
        branch: branchName,
      }
    );

    // 10. Open Pull Request targeting the default branch
    const prBody = buildPRBody({
      incident_id,
      error_type,
      error_message: error_message || '',
      ai_root_cause_summary,
      file_path,
      stack_trace: stack_trace || '',
      dashboard_url: dashboardUrl,
    });

    const prData = await githubAPI(
      'POST',
      `/repos/${repoOwner}/${repoName}/pulls`,
      githubToken,
      {
        title: `AutoTrace: Automated fix for ${error_type}`,
        head: branchName,
        base: defaultBranch,
        body: prBody,
      }
    );

    // 11. Assign PR to the user ('rajjadhav55')
    try {
      await githubAPI(
        'POST',
        `/repos/${repoOwner}/${repoName}/issues/${prData.number}/assignees`,
        githubToken,
        { assignees: [defaultReviewer] }
      );
    } catch (assignErr) {
      console.warn(`[AutoTrace] Non-fatal: failed to assign PR to ${defaultReviewer}: ${assignErr.message}`);
    }

    // 12. Request reviewers on the PR
    if (reviewers.length > 0) {
      try {
        await githubAPI(
          'POST',
          `/repos/${repoOwner}/${repoName}/pulls/${prData.number}/requested_reviewers`,
          githubToken,
          { reviewers }
        );
      } catch (reviewErr) {
        // Non-fatal: PR was created even if reviewer assignment fails (e.g. author cannot review own PR)
        console.warn(`[AutoTrace] Non-fatal: failed to assign reviewers: ${reviewErr.message}`);
      }
    }

    return res.status(201).json({
      status: 'success',
      pr_url: prData.html_url,
      pr_number: prData.number,
      branch: branchName,
      incident_id,
      target_repo,
    });

  } catch (err) {
    console.error('[AutoTrace Webhook Error]', err);
    return res.status(500).json({
      error: 'Failed to create GitHub PR',
      detail: err.message,
    });
  }
}
