# Generated by Django 5.0.3 on 2026-08-29 20:00

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import triage.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostMortem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('error_signature', models.CharField(max_length=500)),
                ('root_cause', models.TextField()),
                ('resolution', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('api_key', models.CharField(db_index=True, default=triage.models.generate_api_key, editable=False, help_text='Unique API tracking key used by SDK clients to report errors.', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('api_key', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('error_type', models.CharField(max_length=255)),
                ('error_message', models.TextField()),
                ('endpoint', models.CharField(blank=True, max_length=500, null=True)),
                ('runtime', models.CharField(blank=True, default='python', max_length=50, null=True)),
                ('traceback', models.JSONField(blank=True, default=list)),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Triage'), ('ANALYZING', 'Analyzing with AI Agent'), ('TRIAGED', 'Triaged'), ('FAILED', 'Triage Failed'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20)),
                ('root_cause', models.TextField(blank=True, null=True)),
                ('suggested_fix', models.TextField(blank=True, null=True)),
                ('http_method', models.CharField(blank=True, max_length=10, null=True)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('diagnostic_logs', models.JSONField(blank=True, default=dict)),
                ('jira_key', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='triage.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_name', models.CharField(db_index=True, default='default-app', max_length=255)),
                ('error_type', models.CharField(db_index=True, max_length=255)),
                ('error_message', models.TextField()),
                ('stack_trace', models.TextField(help_text='Stack trace string.')),
                ('endpoint', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('environment', models.CharField(db_index=True, default='production', max_length=64)),
                ('runtime', models.CharField(blank=True, default='python', max_length=64)),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('UNRESOLVED', 'Unresolved'), ('INVESTIGATING', 'Investigating'), ('RESOLVED', 'Resolved'), ('IGNORED', 'Ignored')], db_index=True, default='UNRESOLVED', max_length=20)),
                ('root_cause', models.TextField(blank=True, null=True)),
                ('suggested_fix', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='The user account that owns the application reporting the error.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='error_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='triage_erro_user_id_f61dc0_idx'), models.Index(fields=['user', 'status'], name='triage_erro_user_id_483ad9_idx'), models.Index(fields=['user', 'application_name'], name='triage_erro_user_id_1ee963_idx')],
            },
        ),
    ]
