# Generated by Django 5.0.3 on 2026-08-21 22:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('error_type', models.CharField(max_length=255)),
                ('error_message', models.TextField()),
                ('traceback', models.TextField()),
                ('endpoint', models.CharField(blank=True, max_length=500, null=True)),
                ('http_method', models.CharField(blank=True, max_length=10, null=True)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Triage'), ('ANALYZING', 'Analyzing with AI Agent'), ('TRIAGED', 'Triaged'), ('FAILED', 'Triage Failed'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20)),
                ('root_cause', models.TextField(blank=True, null=True)),
                ('suggested_fix', models.TextField(blank=True, null=True)),
                ('diagnostic_logs', models.JSONField(blank=True, default=dict)),
                ('jira_key', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostMortem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('error_signature', models.CharField(max_length=500)),
                ('root_cause', models.TextField()),
                ('resolution', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
