# Generated by Django 5.0.3 on 2026-08-27 07:37

import django.db.models.deletion
import secrets
from django.db import migrations, models


def create_default_project(apps, schema_editor):
    Project = apps.get_model('triage', 'Project')
    Incident = apps.get_model('triage', 'Incident')
    default_proj, _ = Project.objects.get_or_create(
        name='Default Project',
        defaults={'api_key': f'autotrace_pk_{secrets.token_hex(20)}'}
    )
    Incident.objects.filter(project__isnull=True).update(project=default_proj)


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('api_key', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='incident',
            name='context_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='incident',
            name='runtime',
            field=models.CharField(blank=True, default='python', max_length=50, null=True),
        ),
        migrations.RunSQL(
            sql='ALTER TABLE triage_incident ALTER COLUMN traceback TYPE jsonb USING to_jsonb(traceback);',
            reverse_sql='ALTER TABLE triage_incident ALTER COLUMN traceback TYPE text USING traceback::text;',
            state_operations=[
                migrations.AlterField(
                    model_name='incident',
                    name='traceback',
                    field=models.JSONField(blank=True, default=list),
                ),
            ],
        ),
        migrations.AddField(
            model_name='incident',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='triage.project'),
        ),
        migrations.RunPython(create_default_project, migrations.RunPython.noop),
    ]
